fix inputs

diff --git a/.github/workflows/update-valkey-hashes.yml b/.github/workflows/update-valkey-hashes.yml
--- a/.github/workflows/update-valkey-hashes.yml
+++ b/.github/workflows/update-valkey-hashes.yml
@@ -16,6 +16,13 @@ jobs:
   commit-hash:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate inputs
+        run: |
+          if [[ ! "${{ github.event.inputs.version }}" =~ ^([0-9]+\.[0-9]+\.[0-9]+|unstable)$ ]]; then
+            echo "Invalid version format. Expected format: x.y.z or 'unstable'"
+            exit 1
+          fi
+          
       - uses: actions/checkout@v4
         with:
           repository: Autxmaton/valkey-hashes
@@ -23,7 +30,7 @@ jobs:
 
       - name: Trigger commit
         run: |
-          VERSION=${{ inputs.version }}
+          VERSION=${{ github.event.inputs.version }}
           URL="https://github.com/Autxmaton/valkey/archive/refs/tags/${VERSION}.tar.gz"
           FILENAME="valkey-${VERSION}.tar.gz"
           wget -O $FILENAME $URL
