make sure sha doesn't get updated twice
Signed-off-by: vudiep411 <vudiep411@gmail.com>

diff --git a/.github/workflows/update-valkey-hashes.yml b/.github/workflows/update-valkey-hashes.yml
--- a/.github/workflows/update-valkey-hashes.yml
+++ b/.github/workflows/update-valkey-hashes.yml
@@ -23,6 +23,22 @@ jobs:
             exit 1
           fi
 
+      - uses: actions/checkout@v4
+        with:
+          repository: Autxmaton/valkey-hashes
+          token: ${{ secrets.PAT_TOKEN }}
+
+      - name: Ensure repository is initialized
+        run: |
+          if [ ! -d ".git" ]; then
+            echo "Error: Not a git repository."
+            exit 1
+          fi
+          if [ ! -f README ]; then
+            echo "README file not found. Creating a new README file."
+            touch README
+          fi
+
       - name: Update hash
         run: |
           set -e
@@ -39,11 +55,6 @@ jobs:
           # Add hash to README if not already present
           if ! grep -q "$HASH $URL" README; then
             echo "hash $FILENAME sha256 $HASH $URL" >> README
-            git config user.name "github-actions[bot]"
-            git config user.email "github-actions[bot]@users.noreply.github.com"
-            git add README
-            git commit -m "Update hash for ${{ inputs.version }}"
-            git push
           else
             echo "Hash entry already exists in README. Skipping append."
           fi
@@ -51,4 +62,13 @@ jobs:
           # Clean up the downloaded file
           rm "$FILENAME"
 
-
+      - name: Commit and push changes
+        run: |
+          set -e
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add README
+          git commit -m "Update hash for ${{ inputs.version }}"
+          git push origin HEAD
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
